# Generated by Django 4.2.3 on 2023-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_users_address_users_pincode_users_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadhar_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='alternate_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='guardian_contact_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.BigIntegerField(null=True, verbose_name='phone number'),
        ),
    ]
