# Generated by Django 4.2.3 on 2023-07-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_users_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadhar_number',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='alternate_number',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='guardian_contact_number',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(null=True, verbose_name='phone number'),
        ),
    ]
