# Generated by Django 4.2.3 on 2023-08-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_users_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
